[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_utils"
description = "A simple utility package for PyTorch"
version = "0.0.1"
dependencies = ["torch", "torchvision", "numpy", "tqdm"]
